/* NEV Absenku V13 - fast login, 30s polling, explicit pending queue */
const CLOUD_SCRIPT_URL="https://script.google.com/macros/s/AKfycby5iQt8AxuGmH6Xup3QvLOU1Op8VxnM9vxt4eqBVTmn0lMSTpfvtdYBXSPVOs1fx3lDKQ/exec";
const cloudSyncEnabled=/^https?:/i.test(CLOUD_SCRIPT_URL);
const CLOUD_POLL_MS=30000;
const CLOUD_QUEUE_KEY="nev_sync_queue_v13";
const CLOUD_ACTION_BY_KEY={[DB.sessions]:"saveSessions",[DB.attendance]:"saveAttendance",[DB.settings]:"saveSettings",[DB.permits]:"savePermits"};
let cloudPollTimer=null,cloudSyncBusy=false,cloudServerVersion=null,cloudLastSyncAt=null,cloudLastError=null,cloudUnsynced=0,cloudQueueBusy=false;
function getAuthToken(){return localStorage.getItem("nev_auth_token")||""}
function clearAuthSession(){localStorage.removeItem("nev_auth_token");localStorage.removeItem("nev_current_user")}
function readQueue(){try{const q=JSON.parse(localStorage.getItem(CLOUD_QUEUE_KEY)||"[]");return Array.isArray(q)?q:[]}catch(e){return[]}}
function writeQueue(q){localStorage.setItem(CLOUD_QUEUE_KEY,JSON.stringify(q));cloudUnsynced=q.length;updateCloudBadge()}
function enqueueCloud(action,data){const q=readQueue(),item={id:"Q-"+Date.now()+"-"+Math.random().toString(36).slice(2,8),action,data,createdAt:new Date().toISOString()};if(["saveSessions","saveAttendance","saveSettings","savePermits"].includes(action)){const i=q.findIndex(x=>x.action===action);if(i>=0)q[i]=item;else q.push(item)}else{const exists=q.some(x=>x.action===action&&x.data&&data&&x.data.id===data.id);if(!exists)q.push(item)}writeQueue(q)}
function removeQueueId(id){writeQueue(readQueue().filter(x=>x.id!==id))}
function cloudPayload(action,data){const body={action,data};if(action!=="login"){const t=getAuthToken();if(t)body.authToken=t}return JSON.stringify(body)}
async function cloudPost(action,data={},retries=0){let last;for(let i=0;i<=retries;i++){try{const r=await fetch(CLOUD_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:cloudPayload(action,data),cache:"no-store"});const t=await r.text();let j;try{j=JSON.parse(t)}catch(e){throw new Error("Respons server bukan JSON.")}if(j&&j.authExpired){clearAuthSession();if(typeof currentUser!=="undefined")currentUser=null;throw Object.assign(new Error("Sesi login telah berakhir."),{authExpired:true,fatal:true})}if(!j||!j.ok)throw Object.assign(new Error(j?.error||"Server menolak permintaan."),{fatal:true});return j}catch(e){last=e;if(e.fatal||i>=retries)break;await new Promise(r=>setTimeout(r,700))}}throw last||new Error("Request gagal")}
async function pushToCloud(key,data){if(!cloudSyncEnabled||!getAuthToken())return;const action=CLOUD_ACTION_BY_KEY[key];if(!action)return;try{await cloudPost(action,data,0);cloudLastError=null;updateCloudBadge()}catch(e){console.error("[V13] sync gagal:",e);enqueueCloud(action,data);cloudLastError=String(e.message||e);updateCloudBadge()}}
const _localSaveV13=save;save=function(key,data){_localSaveV13(key,data);pushToCloud(key,data)};
const _wibDateV13=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"});
const _wibTimeV13=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Jakarta",hour:"2-digit",minute:"2-digit",hourCycle:"h23"});
const _isoV13=/^\d{4}-\d{2}-\d{2}T/;
function fixDateFieldV13(v){if(typeof v==="string"&&_isoV13.test(v)){const d=new Date(v);if(!isNaN(d))return _wibDateV13.format(d)}return v}
function fixTimeFieldV13(v){if(typeof v==="string"&&_isoV13.test(v)){const d=new Date(v);if(!isNaN(d))return _wibTimeV13.format(d)}return v}
function sanitizeCloudDataV13(j){(j.sessions||[]).forEach(s=>{s.date=fixDateFieldV13(s.date);s.start=fixTimeFieldV13(s.start);s.end=fixTimeFieldV13(s.end)});(j.attendance||[]).forEach(a=>a.date=fixDateFieldV13(a.date));(j.permits||[]).forEach(p=>p.sessionDate=fixDateFieldV13(p.sessionDate));return j}
function mergeQueueV13(list,action){const m=new Map((list||[]).filter(x=>x&&x.id).map(x=>[x.id,x]));readQueue().forEach(q=>{if(q.action===action&&Array.isArray(q.data))q.data.forEach(x=>x&&x.id&&m.set(x.id,x));if(q.action==="addAttendance"&&action==="saveAttendance"&&q.data?.id)m.set(q.data.id,q.data);if(q.action==="addPermit"&&action==="savePermits"&&q.data?.id)m.set(q.data.id,q.data)});return[...m.values()]}
async function fetchCloudAll(){if(!cloudSyncEnabled||!getAuthToken())return false;try{const r=await fetch(`${CLOUD_SCRIPT_URL}?action=getAll&authToken=${encodeURIComponent(getAuthToken())}&_=${Date.now()}`,{cache:"no-store"});const j=await r.json();if(j?.authExpired){clearAuthSession();if(typeof currentUser!=="undefined")currentUser=null;return false}if(!j?.ok)throw new Error(j?.error||"Respons tidak valid");sanitizeCloudDataV13(j);_localSaveV13(DB.users,j.users||[]);_localSaveV13(DB.sessions,mergeQueueV13(j.sessions||[],"saveSessions"));_localSaveV13(DB.attendance,mergeQueueV13(j.attendance||[],"saveAttendance"));_localSaveV13(DB.settings,j.settings||{officeLat:null,officeLng:null,radius:100,geofenceEnabled:false});_localSaveV13(DB.permits,mergeQueueV13(j.permits||[],"savePermits"));cloudServerVersion=String(j.version||"").trim()||null;cloudLastSyncAt=new Date();cloudLastError=null;cloudUnsynced=readQueue().length;updateCloudBadge();return true}catch(e){console.error("[V13] getAll:",e);cloudLastError=String(e.message||e);updateCloudBadge();return false}}
async function flushCloudQueue(){if(cloudQueueBusy||!getAuthToken())return;const q=readQueue();if(!q.length){cloudUnsynced=0;updateCloudBadge();return}cloudQueueBusy=true;for(const item of [...q]){try{await cloudPost(item.action,item.data,0);removeQueueId(item.id)}catch(e){console.error("[V13] queue gagal:",item.action,e)}}cloudQueueBusy=false;cloudUnsynced=readQueue().length;updateCloudBadge()}
function startCloudPolling(){if(!cloudSyncEnabled||cloudPollTimer)return;cloudPollTimer=setInterval(async()=>{if(cloudSyncBusy)return;await fetchCloudAll();await flushCloudQueue();if(typeof currentUser!=="undefined"&&currentUser&&typeof renderAll==="function")renderAll()},CLOUD_POLL_MS)}
function updateCloudBadge(){let el=document.getElementById("cloudBadge");if(typeof currentUser==="undefined"||!currentUser){if(el)el.remove();return}if(!el){el=document.createElement("button");el.id="cloudBadge";el.type="button";el.onclick=()=>manualCloudRefresh(false);el.style.cssText="position:fixed;left:12px;bottom:12px;z-index:9999;border:0;border-radius:999px;padding:8px 14px;font:600 12px Inter,sans-serif;cursor:pointer;box-shadow:0 2px 10px rgba(0,0,0,.3);max-width:calc(100vw - 24px)";document.body.appendChild(el)}let text,bg="#2e7d32";if(!cloudSyncEnabled){text="⚠ MODE OFFLINE";bg="#c62828"}else if(cloudUnsynced>0){text="⏳ "+cloudUnsynced+" data belum terkirim — dicoba tiap 30 detik";bg="#ef6c00"}else if(cloudLastError){text="⚠ Gagal sinkron — ketuk untuk coba lagi";bg="#c62828"}else{text="☁ Tersinkron "+(cloudLastSyncAt?cloudLastSyncAt.toLocaleTimeString("id-ID"):"-")+" · ketuk untuk segarkan"}el.textContent=text;el.style.background=bg;el.style.color="#fff"}
async function manualCloudRefresh(silent){if(!cloudSyncEnabled||cloudSyncBusy)return;const ok=await fetchCloudAll();await flushCloudQueue();if(ok&&currentUser&&typeof renderAll==="function")renderAll();if(!silent&&typeof toast==="function")toast(ok?"Data berhasil disegarkan dari Google Sheets.":"Gagal mengambil data dari Google Sheets.",ok?"success":"error")}
/* Fast login: dashboard muncul setelah endpoint login; getAll background. */
window.login=async function(event){event?.preventDefault();const username=(document.getElementById("loginUsername")?.value||"").trim(),password=document.getElementById("loginPassword")?.value||"";if(!username||!password){toast?.("Username/NIM dan password wajib diisi.","error");return}const btn=event?.submitter||document.querySelector('#loginScreen button[type="submit"]');if(btn){btn.disabled=true;btn.dataset.old=btn.innerHTML;btn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Memproses...'}try{const j=await cloudPost("login",{username,password,role:typeof loginRole!=="undefined"?loginRole:"STAF"},0);if(!j?.ok||!j.user)throw new Error(j?.error||"Login gagal");currentUser=j.user;if(j.authToken)localStorage.setItem("nev_auth_token",j.authToken);localStorage.setItem("nev_current_user",JSON.stringify(currentUser));document.getElementById("loginScreen")?.classList.add("hidden");document.getElementById("app")?.classList.remove("hidden");buildSidebar();updateUserUI();if(currentUser.role==="STAF")showPage("staf-dashboard");else if(currentUser.role==="HRD")showPage("hrd-dashboard");else if(currentUser.role==="KOOR KP")showPage("koor-dashboard");renderAll();updateCloudBadge();queueMicrotask(async()=>{const ok=await fetchCloudAll();if(ok&&currentUser)renderAll()})}catch(e){console.error("[V13] login",e);toast?.(String(e.message||e),"error")}finally{if(btn){btn.disabled=false;btn.innerHTML=btn.dataset.old||"Masuk"}}};
/* Server version is informational only: no hard-coded secure-v3 comparison. */
async function bootWithCloudV13(){if(!cloudSyncEnabled){initializeDatabase();return}try{const r=await fetch(`${CLOUD_SCRIPT_URL}?action=bootstrap&_=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(j?.ok){cloudServerVersion=String(j.version||"").trim()||null;_localSaveV13(DB.settings,j.settings||{officeLat:null,officeLng:null,radius:100,geofenceEnabled:false})}}catch(e){console.warn("[V13] bootstrap",e)}const token=getAuthToken(),saved=localStorage.getItem("nev_current_user");if(token&&saved){try{currentUser=JSON.parse(saved);if(await fetchCloudAll()){const valid=(load(DB.users)||[]).find(u=>u.id===currentUser.id);if(valid){currentUser=valid;localStorage.setItem("nev_current_user",JSON.stringify(valid));document.getElementById("loginScreen")?.classList.add("hidden");document.getElementById("app")?.classList.remove("hidden");buildSidebar();updateUserUI();if(currentUser.role==="STAF")showPage("staf-dashboard");else if(currentUser.role==="HRD")showPage("hrd-dashboard");else showPage("koor-dashboard");renderAll()}else{clearAuthSession();currentUser=null}}else{clearAuthSession();currentUser=null}}catch(e){clearAuthSession();currentUser=null}}else initializeDatabase();cloudUnsynced=readQueue().length;updateCloudBadge();startCloudPolling()}
bootWithCloudV13();
